wandb_version: 1

exp:
  desc: null
  value: neorl-hopper
env:
  desc: null
  value: neorl-hopper
dataset:
  desc: null
  value: high
dataset_path:
  desc: null
  value: /content/gdrive/Shareddrives/DRL/decision-transformer/gym/data/offline-data/Hopper-v3-high-v3-10000_trajs.pkl
mode:
  desc: null
  value: normal
K:
  desc: null
  value: 20
pct_traj:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 64
model_type:
  desc: null
  value: dt
embed_dim:
  desc: null
  value: 128
n_layer:
  desc: null
  value: 3
n_head:
  desc: null
  value: 1
activation_function:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0001
warmup_steps:
  desc: null
  value: 10000
num_eval_episodes:
  desc: null
  value: 100
max_iters:
  desc: null
  value: 10
num_steps_per_iter:
  desc: null
  value: 10000
device:
  desc: null
  value: cuda
log_to_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682899522.55763
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.0
      6: 4.28.1
      8:
      - 5
